### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére

### ISSUE THREAD

**Issue by ferencmarkizay** [kigyoteve/QuickGraph#1]

**Comment by kopariadam** [comment]
https://github.com/kigyoteve/QuickGraph/commit/c76a8c5f1664b996c6bb5c81596afe64a72efa8b
Useless lambda

**Comment by kopariadam** [comment]
A Dijktra algoritmusban nem találtam hibát.

**Comment by kopariadam** [comment]
A Dag shortest path algoritmusban nem találtam hibát.

**Comment by MakkiViktor** [comment]
Best first frontier search algoritmusban nem találtam hibát

**Comment by MakkiViktor** [comment]
Bidirectional deepth first search algoritmusban nem találtam hibát

**Comment by MakkiViktor** [comment]
Breadth first search algoritmusban nem találtam hibát

**Comment by ferencmarkizay** [comment]
A munkát ellenőríztem.

**Comment by micskeiz** [comment]
Nehéz megmondani, hogy a review során milyen szempontokat néztetek és mire koncentráltatok.

A wiki lapon jó lenne egy kicsit rendszerezni ezt a részt (milyen szempontok szerint, milyen osztályokat néztetek át, milyen meglátások volt, mi a végeredmény)
