### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák javítása

### ISSUE THREAD

**Issue by ferencmarkizay** [kigyoteve/QuickGraph#2]
SonarQube, FindBugs, VS Code Analyzer, Codacy, Coverity Scan...

**Comment by ferencmarkizay** [comment]
FindBugs és Codacy nem támogatja a C#-ot, a másik hármat kéne lefuttatni.

**Comment by ferencmarkizay** [comment]
Coverity Scan eredmény: https://scan.coverity.com/projects/kigyoteve
Eredmény 1-2 nap múlva.

**Comment by ferencmarkizay** [comment]
VS Code Analyzer 320 hibát talál a https://github.com/kigyoteve/QuickGraph/commit/205f8e29a423dbb1a94228c651ef9e627b956236 commitban feltöltött ruleset-ekkel.
A hibák listája [itt](https://github.com/kigyoteve/QuickGraph/blob/iet-hazi/vs_code_analysis_result.xlsx) található.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/a20c6ab1aa77f1de2625e4e8dd4d501180ec0011 CA1062: A hibák nagy része false positive volt, de ami nem azoknak egy részet kijavítottam.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/3d01b126e5d935d59e7b473eab310beb6f7eee8f CA1012: Absztrak osztályoknak protected konstruktorok.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/41a521de94ac79c915cc5e05f04522e6d4a1c136 CA1024 Paraméter nélküli getterek propertyk legyenek.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/ab92ec732264b821f960e767d8c7e8e8e7bceeea CA1032 Exception-ből származó osztályoknak implementálniuk kell a szükséges konstruktorokat.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/62892d7827f6833512823e8714048cf2b3d3ae26 CA1801: Nem használt paraméterek javítása. Egy helyen nem kerültek mentésre a paraméterek, a többbi helyen eltávolíthatóak voltak.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/a27a48c477671e0ef80ce9b08d47aec2ad13f769 CA1036: IComparable interfészt megvalósító osztályoknak felül kell írnia a GetHashCode, Equals metódusokat, és a !=, ==, <, > operátorokat. Csak az utóbbi kettő sikerült, hiszen nincs az osztálynak egyedi mezője.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/49b24c5dd0061d62689813699411d9ba6a28eb9e CA1053: Full statikus osztályoknak private default konstruktort deklaráltam, ezzel meggátolva, hogy a fordító public default-ot generáljon nekik.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/48c64a92d484e952e1f7a997afdd5f69d71b7412 CA1052: Full statikus osztályok 'sealed' kulcsszóval lettek ellátva, ezzel meggátolva az öröklődést tőlük.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/6ff26c29d117c84020c3dc293cf1f9317f2b819d CA1062: Paraméterek nullsága ellenőrízve.

**Comment by udvaritibor** [comment]
https://github.com/kigyoteve/QuickGraph/commit/a8ab609c7c3e1206d5d856b572750906f20a7965 Felesleges null check + elírás.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/ce29e9de2a25d4941efcfb5caec50d59a8c7c2a4 CA1804: A nem használt változókat kitöröltem, az ellenőrző sok hamis pozitív eredményt adott, ezért ezt a szabály kikapcsoltam.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/19677e56a684d50388b6f7faff48aa32297ee62a CA1811: A nem használt függvényeket eltávolítottam, kivéve, ahol az osztály még fejlesztés alatt van.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/1598923853eb157e97dc34fe708462b93fd37fc4 CA1823: Eltávolítottam a nem használt tagváltozókat, kivéve, ahol debug célból volt benne.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/3c4e00898bf061a0d6a91366905b12f8fbede404 CA2000: Dispose meghívása Disposable objektumokra.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/c0621b7352fde25400306d55a370215896023928 CA2231: Hianyzó == és != operátorok hozzáadása.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/63920c51f7ecde73404035acfabd4aca8d1352d4 CA2235 és CA2237: A nem szerializálható tagváltozóknak nonserialized, a serializálható osztálynak serializable attribútumok.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/3703bf51f0db8ffc5e3e38fc6505e7df038553b3 CA2241: Egy format string-ben három paramétert használt, pedig csak kettő volt átadva.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/047298edf7bfa14993e19edc8c7506520235a4f5 CS0169: Az egyik tesztben szerepelt egy nem használt tagváltozó.

**Comment by ferencmarkizay** [comment]
A Visual Studio code analysis mostmár nem jelez hibát.

**Comment by kopariadam** [comment]
Sealed private constuctoros osztályokból staticot csináltam.

**Comment by kopariadam** [comment]
A változtatásokat átnéztem, nem találtam bennük több hibát.

**Comment by micskeiz** [comment]
Rendben, alaposan végignéztétek a jelzett hibákat.
