### ISSUE TITLE
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

### ISSUE THREAD

**Issue by ferencmarkizay** [kigyoteve/QuickGraph#3]
JaCoCo, OpenCover, Coveralls, Codecov.io.

**Comment by udvaritibor** [comment]
OpenCover eredmények:
Visited Classes 131 of 189 (69.31)
Visited Methods 616 of 1077 (57.2)
Visited Points 5260 of 8674 (60.64)
Visited Branches 852 of 1788 (47.65)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 139 of 195 (71.28)
Alternative Visited Methods 777 of 1326 (58.6)

Coverage Results XML: https://file.io/TZvLJY

**Comment by udvaritibor** [comment]
Futtatva az összes namespace-n:
Visited Classes 491 of 874 (56.18)
Visited Methods 2020 of 4808 (42.01)
Visited Points 13543 of 28364 (47.75)
Visited Branches 3554 of 9179 (38.72)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 529 of 955 (55.39)
Alternative Visited Methods 2605 of 6268 (41.56)

Coverage Results XML: https://file.io/ItiSLg

**Comment by ferencmarkizay** [comment]
A kód releváns részének fedettsége 41.92%.
A részletes eredmény [itt](https://codecov.io/gh/kigyoteve/QuickGraph/tree/e7cf278a270855442b227f0cc427b83350799fc8/src/QuickGraph) megtekinthető.

[Link az iet-hazi branch oldalára](https://codecov.io/gh/kigyoteve/QuickGraph/branch/iet-hazi)

**Comment by ferencmarkizay** [comment]
Az Appveyor build-ek frissítik a code coverage-t.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/075ddf666b5b8bfa8fab28e87b6e47332905ecf8: Unit tesztek az UndirectedGraph es BidirectionalGraph osztályokhoz.  

Coverage: 42.54%

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/6a9cac766e932ed003593665cdac789660f938ee, https://github.com/kigyoteve/QuickGraph/commit/c96c9f0f236bc0c594fcdfc3c163086668f41dfa, https://github.com/kigyoteve/QuickGraph/commit/8dc5c8a5c72d90b45277a4c64e8cfefd67d800da: Az AppVeyor config-ot frissítettem, hogy csak a releváns részekre fusson a code coverage.

**Comment by ferencmarkizay** [comment]
https://github.com/kigyoteve/QuickGraph/commit/90d55ff8b82a001d57c75c2df2ab0bcd24bb606e: BidirectionalMatrixGraph unit tesztek.

Coverage: 44,35%

**Comment by udvaritibor** [comment]
SEdgeTest unit test implementálva.
https://github.com/kigyoteve/QuickGraph/commit/8da042cd0b825ed7578d2ac1ac95b10315635681

100 százalékos lefedettség.

**Comment by udvaritibor** [comment]
STaggedEquatableEdge toString() metódusa kiírja a taget is, mint ahogy a többi taggel rendelkező edge-nél.
https://github.com/kigyoteve/QuickGraph/commit/10353f0153160fa37308e88564ef5fc2b72e6eb5

**Comment by udvaritibor** [comment]
STaggedEquatableEdgeTest unit test implementálva.
d1eba4874134fc390cf5734f5938f50b5c7e81dd
Fix:
https://github.com/kigyoteve/QuickGraph/commit/6a729ec6dc6f4a9d419eefdc474601f409c0329d

Coverage: ~95 %

**Comment by udvaritibor** [comment]
SUndirectedTaggedEdge átnevezve STaggedUndirectedEdge-re, hogy konzisztens legyen a többi osztályelnevezéssel.
https://github.com/kigyoteve/QuickGraph/commit/be89024c05987892de18a9ac19d500a73430600d

**Comment by udvaritibor** [comment]
SUndirectedTaggedEdgeTest unit test implementálva.
https://github.com/kigyoteve/QuickGraph/commit/36792549ee890d5971a3f6bd6aef4be2397a7f46

Coverage: ~95 %

**Comment by udvaritibor** [comment]
SUndirectedEdgeTest unit test implementálva.
https://github.com/kigyoteve/QuickGraph/commit/bfb30aa73e12a9637a616dfddaf892a1ab7210a6

Coverage: 100 %

**Comment by udvaritibor** [comment]
SReversedEdgeTest unit test implementálva.
https://github.com/kigyoteve/QuickGraph/commit/669af07798e9432048d62ede245a1298733bd9c3

Coverage: ~85 %

**Comment by udvaritibor** [comment]
Az utóbbi 5 unit test a projekt lefedettségét összesen 0.67 százalékkal emelte.

**Comment by MakkiViktor** [comment]
BidirectionalGraph isOutEdgeEmpty test implementálva.

**Comment by MakkiViktor** [comment]
UndirectedEdge-ben a toString testelve.

**Comment by MakkiViktor** [comment]
UndirectedGraphban IsVerticesEmpty tesztelve.

**Comment by kopariadam** [comment]
A teszteket leellenőriztem, nem találtam benne hibát.
