### ISSUE TITLE
Egység tesztek készítése

### ISSUE THREAD

**Issue by ferencmarkizay** [kigyoteve/QuickGraph#4]

**Comment by kopariadam** [comment]
EdgeListGraph:
Az allowParralelEdges nem csinál semmit.
Ha EquatableEdge-t használunk, akkor a hozzáadásnál allowParralelEdges=false módban működik, ha Edge-t akkor allowParralelEdges=true módba, amennyiben nem ugyan azt a referenciájú élt rakjuk be.
Contains függvény Edge-nél a referenciát hasonlítja össze, EquatableEdge-nél a két végpontot.

**Comment by kopariadam** [comment]
EquateGraph
Ez helyesen működik

**Comment by udvaritibor** [comment]
SEdgeTest unit test implementálva.
https://github.com/kigyoteve/QuickGraph/commit/8da042cd0b825ed7578d2ac1ac95b10315635681

**Comment by MakkiViktor** [comment]
BidirectionalGraph isOutEdgeEmpty test implementálva.
UndirectedEdge-ben a toString testelve.
UndirectedGraphban IsVerticesEmpty tesztelve.

**Comment by MakkiViktor** [comment]
UndirectedGraph removeVertexIf tesztelve

**Comment by ferencmarkizay** [comment]
A munkát ellenőríztem.
